---
name: Acme-Roman
version: v0.0.2
author:
  - 'Adriano R. Ferreira <ferreira@cpan.org>'
abstract: Do maths like Romans did
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Accessor: 0
  Roman: 0
  Scalar::Util: 0
  base: 0
  overload: 0
  strict: 0
  version: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
recommends:
  Test::Pod: 1.18
  Test::Pod::Coverage: 1.04
provides:
  Acme::Roman:
    file: lib/Acme/Roman.pm
    version: v0.0.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
